title: <p align="center"> Bhuvaneshwari S </p>

logo: 
<p align="center"> "/assets/img/avatar.jpg?raw=true" </p>

description: 
  <p align="center">
  <a>Business Analytics</a> |
  <a>Data Science</a> 
  </p>

  <p align="justify">
  *Driven by a commitment to excellence, I seek to harness the power of data analytics to 
  facilitiate informed choices and optimal outcomer to customer.*
  <br><br>
  </p>
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
