title: <p align="left"> Bhuvaneshwari S </p>

logo: "/assets/img/avatar.jpg?raw=true"

description: 
  <p align="left">
  <a>Business Analytics</a> |
  <a>Data Science</a> 
  </p>

  <p align="justify"><i>
  Driven by commitment to excellence, I seek to harness the power of data analytics to 
  facilitiate informed decisions and optimal business outcomes for customers.
  <br><br>
  </i></p>
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
