title: <p align="center"> Bhuvaneshwari S </p>
logo: "/assets/img/avatar.jpg?raw=true"
description: 
  <p align="justify">
  Driven by a commitment to excellence, I seek to harness the power of data analytics to 
  facilitiate informed choices and optimal outcomes.
  <br><br>
  </p>
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
