title: <p align="center"> Bhuvaneshwari S </p>

logo: 
  <div style="text-align: center;">
    ![Image]("/assets/img/avatar.jpg")
  </div>

description: 
  <p align="center">
  <a>Business Analytics</a> |
  <a>Data Science</a> 
  </p>

  <p align="justify">
  *Driven by a commitment to excellence, I seek to harness the power of data analytics to 
  facilitiate informed choices and optimal outcomer to customer.*
  <br><br>
  </p>
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
