title: Bhuvaneshwari
logo: /assets/img/avatar.jpg
description: Driven by a commitment to excellence, I seek to harness the power of data analytics to 
             facilitiate informed choices and optimal outcomes.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
